### ISSUE TITLE
Toggling visibility/rendering

### ISSUE THREAD

**Issue by ATizik** [kwebio/core#40] opened 2018-08-24 16:59 UTC
Hi, just wondering if there is an example of toggling visibility of views, or maybe removing them all together. 

Basically I want something like dropdown menu with dynamically generated elements tied to shoebox, but I'm not sure how to do it properly.

**Comment by sanity** [comment] 2018-08-24 17:15
Happy to help, the documentation isn't as good as it should be yet.

`renderEach` should be useful there, here is an example of its usage: https://github.com/kwebio/core/blob/master/src/main/kotlin/io/kweb/demos/todo/todoApp.kt#L114

Are you using SemanticUI?  Does its [menu]( https://semantic-ui.com/collections/menu.html) functionality fit your needs?

**Comment by sanity** [comment] 2018-08-24 18:33
You can enable or disable an element: https://github.com/kwebio/core/blob/master/src/main/kotlin/io/kweb/dom/element/Element.kt#L184

Is that what you need?

**Comment by ATizik** [comment] 2018-08-27 07:49
I guess that'll work, but I can't seem to get it to work with `getElementById`
When I create an element like this 
```div(mapOf("id" to uid)).new {...```
 and then call
```browser.doc.getElementById(uid).disable()```
Nothing happens

**Comment by sanity** [comment] 2018-08-27 08:03
Hmm, I'm not sure why that wouldn't work.  Can you give me a complete stand-alone code snippet that illustrates the problem?  With that I could try to reproduce and diagnose.

Have you tried something like this:

```
val myDiv = div().new { ... }

myDiv.disable()
```

**Comment by ATizik** [comment] 2018-08-27 08:18
You're right, it does work, I just needed to delete element to hide it completely instead of greying it out. So, I guess my question is, can I somehow check whether `.delete()` or `.deleteIfExists()` actually deleted an element? I can, of course, store toggleable divs in some array, but i'd rather avoid it, it could get out of sync from actual state on screen.

**Comment by sanity** [comment] 2018-08-27 08:28
Hmm, it seems like you're trying to do state management manually that should be handled by the framework.

Can you give me some more context on what you're trying to achieve?  I have a feeling there might be an easier way, but I still don't really understand the problem you're trying to solve.

For example, `renderEach` will automatically add, remove, and reorder elements in response to changes in Shoebox state, so if you can use it - you get all that for free.

**Comment by sanity** [comment] 2018-08-27 08:29
Perhaps you could share the relevant code in-context?

**Comment by sanity** [comment] 2018-08-27 08:42
In general, note that you can always evaluate an arbitrary JavaScript expression within the browser using `evaluate()`, it will return a Future with the result - so you could use that to test for element presence.

But I have a feeling there is a better way here, so I'll wait to see if you can give me some more context.

**Comment by ATizik** [comment] 2018-08-27 09:12
I'm trying to achieve a toggleable div on my screen. 
When I turn toggle on/off I want to show/hide my div.


```
private fun ElementCreator<*>.renderDropList(uid: String) {

    val list = try {
        toVar(State.refLists, uid)
    } catch (e: Throwable) {
        val newListId = createNewDropList()
        toVar(State.refLists, newListId)
    }

   //here is a missing piece
   //pseudocode
   val element = doc.elementById(uid)
   if(element != null) {
       element.delete()
       return
   }
   //pseudocode end

    div(mapOf("id" to uid)).new {
        div(semantic.ui.left.aligned.divided.list).new {
            renderEach(State.refsByList(list.value.uid)) { item ->

                div(semantic.item).new {
                    div(semantic.content).text(item.map(State.CrossRef::text))
                }
            }
        }
}
```

So, if an element is already rendered, on click of a toggle I should delete them, otherwise render them again.

**Comment by sanity** [comment] 2018-08-27 09:25
Ah, ok - a few questions:

What is the type of the `list` value?  It will be `KVar<?>`, let's say it is `KVar<RefList>` for now.

Does `RefList` have a `val` to indicate whether it is toggled on or off?  eg.

```kotlin
enum class Toggle { ON, OFF }

data class RefList(val uid : String, val name : String, val toggle : Toggle)
```

(You could also just use a boolean for `toggle`, but I like to be more explicit when I can.

**Comment by sanity** [comment] 2018-08-27 09:29
Oh, I guess I skipped a question.

Is this toggled state intended to be global across all users, or local to this user, or just local to this browser session?

**Comment by ATizik** [comment] 2018-08-27 09:42
Local to browser session, that's why I don't want to store it in shoebox. Although I'm now interested how to achieve local to user state, but that's not really relevant to me :)

**Comment by ATizik** [comment] 2018-08-27 11:31
It's in a list similar to your todo example:

```
div(semantic.right.floated.content).new {
    renderDropDown(item.value.uid)
}


private fun ElementCreator<DivElement>.renderDropDown(uid: String) {

    val button = button(semantic.mini.ui.icon.button)

    button.new {
        i(semantic.toggle.icon)
    }

    button.on.click {
        renderDropList(uid)
    }
}
```

**Comment by ATizik** [comment] 2018-08-27 13:06
Anyway, I ended up solving my problem like this:
```
        val exists = browser.evaluate(
                """
                document.getElementById("$uid")!=null;
                """).await()
        if(exists=="true") {
            browser.doc.getElementById(uid).delete()
            return@launch
        }
```
Thanks for help!
I hope I can share my work with kweb on github in the future

**Comment by sanity** [comment] 2018-08-27 13:17
Ah, getting it working is the important thing.

I think you could take advantage of KVar and `render` here, which takes a KVar and will automatically re-render the contents of automatically

```kotlin
    val isToggledKVar = KVar(true)

    render(isToggledKVar) { toggled ->
       if (toggled) {
           renderDropList(uid)
       } else {
           // Won't render
       }
    }
        
    val button = button(semantic.mini.ui.icon.button)

    button.new {
        i(semantic.toggle.icon)
    }

    button.on.click {
        // This will automatically cause 
        isToggled.value = !isToggled.value
    }
}
```

**Comment by sanity** [comment] 2018-09-15 13:46
I'm going to close this for now, please re-open if necessary.

**Closed by sanity** 2018-09-15 13:46 UTC
